yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/',
        views.UserPasswordChange.as_view(),
        name='password_change_form'
    ),
    path(
        'password_change/done/',
        views.UserPasswordChangeDone.as_view(),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        views.UserPasswordReset.as_view(),
        name='password_reset_form'
    ),
    path(
        'password_reset/done/',
        views.UserPasswordResetDone.as_view(),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        views.UserPasswordResetConfirm.as_view(),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        views.UserPasswordResetComplete.as_view(),
        name='password_reset_complete'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler403 = 'core.views.csrf_failure'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.handler500'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/users/views.py
from django.contrib.auth.views import (PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CreationForm

PASSWORD_ACTIONS_TEMPLATE = 'users/password_change.html'


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'


class UserPasswordChange(PasswordChangeView):
    template_name = PASSWORD_ACTIONS_TEMPLATE

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title_text'] = 'Изменение пароля'
        context['card_header_text'] = 'Изменить пароль'
        context['button_text'] = 'Изменить пароль'
        return context


class UserPasswordChangeDone(PasswordChangeDoneView):
    template_name = PASSWORD_ACTIONS_TEMPLATE

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title_text'] = 'Пароль изменён'
        context['card_header_text'] = 'Пароль изменён'
        context['notification_text'] = 'Пароль изменён успешно'
        return context


class UserPasswordReset(PasswordResetView):
    template_name = PASSWORD_ACTIONS_TEMPLATE

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title_text'] = 'Сброс пароля'
        context['card_header_text'] = (
            'Чтобы сбросить старый пароль — введите адрес электронной почты, '
            'под которым вы регистрировались'
        )
        context['button_text'] = 'Изменить пароль'
        return context


class UserPasswordResetDone(PasswordResetDoneView):
    template_name = PASSWORD_ACTIONS_TEMPLATE

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title_text'] = 'Сброс пароля прошёл успешно'
        context['card_header_text'] = 'Отправлено письмо'
        context['notification_text'] = (
            'Проверьте свою почту, вам должно прийти письмо '
            'со ссылкой для восстановления пароля'
        )
        return context


class UserPasswordResetConfirm(PasswordResetConfirmView):
    template_name = PASSWORD_ACTIONS_TEMPLATE

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title_text'] = 'Новый пароль'

        if(context['validlink']):
            context['card_header_text'] = 'Введите новый пароль'
            context['button_text'] = 'Назначить новый пароль'
        else:
            context['card_header_text'] = 'Ошибка'
            context['notification_text'] = (
                'Ссылка сброса пароля содержит ошибку или устарела.'
            )
        return context


class UserPasswordResetComplete(PasswordResetCompleteView):
    template_name = PASSWORD_ACTIONS_TEMPLATE

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title_text'] = 'Сброс пароля прошёл успешно'
        context['card_header_text'] = 'Отправлено письмо'
        context['notification_text'] = (
            'Ваш пароль был сохранен. Используйте его для входа'
        )
        return context

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title_text %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div>
    </div>
  </div>
</div>
{% endblock %} 

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title_text %}Войти{% endblock %}
{% block content %}
  {% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/users/password_change.html
{% extends 'base.html' %}
{% block title_text %} {{ title_text }} {% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {{ card_header_text }}
        </div>
        <div class="card-body">
          {% if form %}
            {% include 'users/includes/user_form.html' %}
          {% else %}
            <p>{{ notification_text }}</p>
            {% if request.resolver_match.view_name == 'users:password_reset_complete' %}
              <a href="{% url 'users:login' %}">войти</a>
            {% endif %}
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title_text %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        {% load user_filters %}
        <div class="card-header">
          Зарегистрироваться
        </div>
        <div class="card-body">
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}            
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}

            <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}
              {% for field in form %}
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>    
                {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}